name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  commit-hash:
    runs-on: ubuntu-latest
    outputs:
      commit_hash: ${{ steps.get_commit.outputs.commit_hash }}
    steps:
      - uses: actions/checkout@v4
      - name: Get commit hash
        id: get_commit
        run: echo "::set-output name=commit_hash::$(git rev-parse HEAD)"

  client-tests:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./client

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        cache-dependency-path: ./client/package-lock.json
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run Linter
      run: npm run lint
      
    - name: Check Formatting
      run: npm run format:check

    - name: Run Tests
      run: npm test

    - name: Build
      run: npm run build

  server-tests:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    defaults:
      run:
        working-directory: ./server

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        cache-dependency-path: ./server/package-lock.json
        
    - name: Install dependencies
      run: npm ci

    - name: Generate Prisma Client
      run: npm run db:generate

    - name: Set up Database
      run: npx prisma db push --force-reset
      env:
        DATABASE_URL: "postgresql://postgres:postgres@localhost:5432/testdb"

    - name: Run Linter
      run: npm run lint 

    - name: Check Formatting
      run: npm run format:check

    - name: Run Tests
      run: npm test
      env:
        DATABASE_URL: "postgresql://postgres:postgres@localhost:5432/testdb"

  build-and-push-image:
    needs:
      - client-tests
      - server-tests
      - commit-hash
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set short git commit SHA
        id: vars
        run: |
          calculatedSha=$(git rev-parse --short ${{ github.sha }})
          echo "COMMIT_SHORT_SHA=$calculatedSha" >> $GITHUB_ENV

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build client Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./client
          push: true
          tags: |
            ghcr.io/${{ toLower(github.repository) }}-client:${{ needs.commit-hash.outputs.commit_hash }}
            ghcr.io/${{ toLower(github.repository) }}-client:latest

      # Build server Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./server
          push: true
          tags: |
            ghcr.io/${{ toLower(github.repository) }}-server:${{ needs.commit-hash.outputs.commit_hash }}
            ghcr.io/${{ toLower(github.repository) }}-server:latest
